version: '3'
services:
    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        build:
            context: ./docker/nginx/
        ports:
            - '${NGINX_EXT_PORT}:80'
        logging:
            options:
                max-size: 50m
        restart: always
        labels:
            - traefik.backend=api
            - traefik.frontend.rule=Host:api.chat-up.online
            - traefik.docker.network=web
        networks:
            - web
            - in
        volumes:
            - ./:/var/www/html
            - phpsocket:/var/run
    php-fpm:
        container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
        build:
            context: ./docker/php-fpm/
            dockerfile: Dockerfile
            target: php81-fpm
            args:
                UID: '${WWWUSER}'
                GID: '${WWWGROUP}'
        networks:
            - in
        labels:
            - traefik.enable=false
        extra_hosts:
            - 'host.docker.internal:host-gateway'
            - 'chat.loc:host-gateway'
        environment:
            - TZ=Europe/Moscow
        logging:
            options:
                max-size: 50m
        restart: always
        volumes:
            - './:/var/www/html'
            - 'phpsocket:/var/run'
        depends_on:
            - mysql
            - redis
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - in
        volumes:
            - './dockerdata/mysql:/var/lib/mysql'
        labels:
            - traefik.enable=false
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        labels:
            - traefik.enable=false
        networks:
            - in
        volumes:
            - 'sail-redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    phpsocket:
networks:
  web:
    external: true
  in:
    external: false

